Basic Prover instructions implementation
Sin7Y/olavm pull request #11
Opened 2022-11-24 08:07 UTC by spartucus

This PR did:
* ADD, MUL, EQ, MOV, JMP, CJMP, MLOAD, MSTORE instructions are basically implemented.
* Some code format.

Need to be done:
* CALL, RET instruction constraints.
* Context constraints like CLK, PC.
* Memory constraint.
* Program constraint.

2022-11-24 09:05 UTC, JiangXb-son commented on prover/src/arithmetic/add.rs
> +    let unreduced_output = builder.add_extension(input0, input1);
Why reuse the circuit of plonky2?

2022-11-24 09:28 UTC, JiangXb-son requested changes

2022-11-24 09:28 UTC, JiangXb-son commented on prover/src/arithmetic/add.rs
> +    let unreduced_output = builder.add_extension(input0, input1);
for u32_add, the trace should be
a + b*1 = d
d_lo + d_hi *2^32 = d
rangecheck(d_lo)
bool(d_hi)

2022-11-24 09:28 UTC, JiangXb-son commented on prover/src/arithmetic/add.rs
> +    let unreduced_output = builder.add_extension(input0, input1);
New version:
for u32_add, the trace should be
a + b * 1 = d
d_lo + d_hi *2^32 = d
d_lo_lo16 + d_lo_hi_16 *2^16 = d_lo
range check(d_lo_lo16, d_lo_hi16)
bool(d_hi)

2022-11-24 09:28 UTC, JiangXb-son commented on prover/src/builtins/range_check_u32.rs
> +    fn range_limbs(&self) -> Range<usize> {
Use lookup argument pls

2022-11-24 11:19 UTC, JiangXb-son commented on prover/src/utils.rs
> +    let trace: Vec<[F; NUM_INST_COLS]> = steps
trace should be vec<vec<>>?

2022-11-28 02:45 UTC, Softcloud88 commented on prover/src/flow/flow_stark.rs
> +        yield_constr.constraint(nv[COL_CLK] * (nv[COL_CLK] - lv[COL_CLK] - P::ONES));
Should put this constraint and jmp logic into a CpuStark.

2022-11-28 10:12 UTC, merged